{{- range $name, $secret := .Values.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  encryptedData:
    {{- range $key, $value := $secret -}}
    {{- /* Filter out _type key */ -}}
    {{- if ne $key "_type" }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: {{ $.Values.namespace }}-{{ $name }}
      name: {{ $name }}
      namespace: {{ $.Values.namespace }}
    {{- if $secret._type }}
    type: {{ $secret._type }}
    {{- end }}
{{- end }}