{{- range $name, $data := .Values.services }}
{{- if $data.pipeline }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: {{ $.Values.namespace }}-{{ $name }}-git-event
  namespace: tekton-pipelines
spec:
  triggers:
    - name: github-listener
      interceptors:
        - params:
            - name: eventTypes
              value:
                - push
                - pull_request
          ref:
            kind: ClusterInterceptor
            name: github
      template:
        ref: git-event-template
      bindings:
        - name: pipelineName
          value: {{ $.Values.namespace }}-{{ $name }}
        - name: gitUrl
          value: {{ $.Values.git }}
        - name: pathToContext
          value: {{ $data.pipeline.context }}
        - name: dockerfile
          value: {{ $data.pipeline.dockerfile }}
        - name: deploymentName
          value: {{ $name }}
        - name: namespace
          value: {{ $.Values.namespace }}
        - name: imageUrl
          value: {{ $data.image.repo }}
        - name: imageTag
          value: {{ $data.image.tag }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  name: {{ $.Values.namespace }}-{{ $name }}-githook-ingress
  namespace: tekton-pipelines
spec:
  ingressClassName: nginx
  rules:
    - host: github.{{ $data.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: el-{{ $.Values.namespace }}-{{ $name }}-git-event
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - github.{{ $data.ingress.host }}
      secretName: {{ $.Values.namespace }}-{{ $name }}-githook-tls
{{- end }}
{{- end }}